### ISSUE TITLE
About training epoch

### ISSUE THREAD

**Issue by pokameng** [CompVis/latent-diffusion#194]
I can't find the epoch set for the training in .yaml file (e.g. lsun_bedroom-ldm-vq-4.yaml). How do we now the epoch of training and change it?
 How many epochs will the programe end?
@rromb @asanakoy @pesser @crowsonkb @theRealSuperMario @to3i

**Comment by kapsner** [comment]
You would need to set `max_epochs` in the lightning configs, e.g.

```yaml
lightning:
  trainer:
    gpus: 0,
    log_every_n_steps: 15
    max_epochs: 400
```

This defaults to 1000: https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html#max-epochs
