### ISSUE TITLE
How to train an AE from scratch?

### ISSUE THREAD

**Issue by simon-donike** [CompVis/latent-diffusion#270]
Hello there, I encounter the following issue when trying to train an AE from scratch for a Super-Resolution task. My workflow so far is the following:

1. Instantiate an autoencoderKL class from _ldm/models/autoencoder.py_ via _configs/autoencoder/autoencoder_kl_64x64x3.yaml_
2. Train the AE
3. Instanciate whole AE+UNet model via _models/ldm/bsr_sr/config.yaml_
4. Instanciate AE with pretrained weights from _configs/autoencoder/autoencoder_kl_64x64x3.yaml_
5. In complete model from step 3, switch out model.first_stage_model with trained AE model from step 4
6. Train complete model

My results are quite bad unfortunately. The training of the AE yields good results:
![AE](https://raw.githubusercontent.com/simon-donike/simon-donike/main/data/AE.png)
but when combined with the UNet it does not learn anything:
![SR](https://raw.githubusercontent.com/simon-donike/simon-donike/main/data/SR.png)

**Questions:**

- Any ideas why the previously described issue in the workflow appears?
- When using the pretrained AE and UNet given by the authors in combination with the standard config files from the Repo, it loads an Autoencoder from _ldm/models/autoencoder.py_ of class VQModelInterface. Does my model need to be of class type VQModelInterface too instead of AutoencoderKL? Potentially related to #227
- Should I instead train a AE of class type VQModel? I tried that, but get 'NotImplemented' error since it returns a tuple.
  
Anything pointing me in the right direction would be much appreciated, thanks in advance!

**Comment by simon-donike** [comment]
As it turns out, more training fixes the problem (in my case, ~48hrs on 4xA100). Even though the visual reconstruction of the AE in isolation seems fine, it is still not creating an optimal latent space for SR. Continueing to train solves that issue and leads to good results also in unision with the UNet. I also suggest adding a LR scheduler to the training of the AE.

**Comment by pseudo-usama** [comment]
Is AE good for super resolution tasks?

**Comment by simon-donike** [comment]
As shown by the original authors in the paper - yes. Supposedly _small_ or _no_ quality loss compared to pixel-space diffusion but huge inference speed increase. In my test setup, SR in the latent space increases speed about five-fold.

**Comment by Ljnian** [comment]
Hello, I would like to ask, when you say 'more training', are you referring to training the AE or the U-Net?"

**Comment by simon-donike** [comment]
Yes, more AE Training time fixed the problem. An important point to take into account is the disc_start parameter in the autoencoder config, which determines after how many steps the discriminator component of the loss should kick in. Experimenting with this setting and the LR schedulers can surely speed up the training by quite a bit.

**Comment by zhenjiaa** [comment]
hello, I would like to ask what version of torch you use when training with A100

**Comment by simon-donike** [comment]
Hi @zhenjiaa, its 1.13.1+cu117.

**Comment by SoHotLB** [comment]
Hello, I would like to inquire whether the loss keeps decreasing throughout the AE training process. I trained the model on my custom dataset for 20 epochs, but the loss seemed to plateau at a relatively high value of around 2000 instead of further decreasing. I set the `disc_start` parameter to 10001, which means it starts after approximately 10 epochs. Could you kindly provide me with information regarding the size of your dataset and the corresponding configuration files? I truly appreciate your assistance.

**Comment by simon-donike** [comment]
Hello @SoHotLB, yes the loss keeps decreasing during the training process. What's a bit tricky is that the recreation loss seems to plateausbefore the KL divergence loss, leading to the issues I encountered in the original ticket opened in this thread.

Dont mind the absloute loss values, i'm using multispectral images with >3 bands. ~200k images. I heavily modified the repo and how it handles the config files, so i doubt that would be useful for you, sorry.  <img width="850" alt="ls" src="https://github.com/CompVis/latent-diffusion/assets/65158680/04bb9c20-ee4c-4c4f-85e9-2aedaa0df040">

**Comment by SoHotLB** [comment]
> Hello @SoHotLB, yes the loss keeps decreasing during the training process. What's a bit tricky is that the recreation loss seems to plateausbefore the KL divergence loss, leading to the issues I encountered in the original ticket opened in this thread.
> 
> Dont mind the absloute loss values, i'm using multispectral images with >3 bands. ~200k images. I heavily modified the repo and how it handles the config files, so i doubt that would be useful for you, sorry. <img alt="ls" width="850" src="https://user-images.githubusercontent.com/65158680/252290974-04bb9c20-ee4c-4c4f-85e9-2aedaa0df040.png">

ok, thanks for your reply. At the same time, I want to know if outputting `pop from empty list` during training affects the result.

**Comment by simon-donike** [comment]
@SoHotLB not sure what you mean by that.

**Comment by SoHotLB** [comment]
@simon-donike like this. #299

**Comment by Xijieupenn** [comment]
May I ask that how did you run the autoencoder alone?

**Comment by simon-donike** [comment]
@xijiewillpass check out the load_model_from_config function from notebook_helpers.py. To that, you can pass an AE config file with the configuration that you want. You can either load the state_dict or a pretrained checkpoint into that instantiated model, or define a ckpt_path in the config file. To train the autoencoder alone, you can pass that model into a PyTorch lightning Trainer together with either your own dataloader/data class, or use one of the author's ones.

**Comment by Xijieupenn** [comment]
@simon-donike Thank you so much. It worked though the result has some noise.

**Comment by songtianhui** [comment]
@simon-donike Hi! I also want to train my custom AE. Where is the code for training AE? Thanks!

**Comment by JinWonjoon** [comment]
@simon-donike 
Hello, simon!
Thanks for sharing your experimental results and insights.

Can you share me configurations of the learning rates and learning rate scheduler?
I think it would be helpful for training AE for my dataset.

Thank you!

**Comment by simon-donike** [comment]
@JinWonjoon Hi, the LR scheduler I use is ReduceOnPlateau, the patience epoch-wise of course depends on your dataset size but should be around 75k-100k steps. I didn't get good results with a fixed LR or with linear schedules, so personally I think it's best to use reduce on plateau. 
Im starting at 0.0001 IIRC. Processing power isn't really a problem for me, so I don't mind if it's not 100 percent efficient. Check out warm-up schedules etc, that might increase the time to convergence by quite a bit. Good luck!

**Comment by simon-donike** [comment]
> @simon-donike Hi! I also want to train my custom AE. Where is the code for training AE? Thanks!

Hi @songtianhui, there is no code in the original repo to train the AE. Check out the reply to @xijiewillpass, that's what worked for me.

**Comment by soyeonjangg** [comment]
hi @simon-donike i want to build a SR model for 128x128 -> 512x512. based on the conversation above i think i have to add more channel in the autoencoder (if im not mistaken?). how can i modify the code and train from scratch for my own need (128x128 -> 512x512) ?

**Comment by ray-lee-94** [comment]
@simon-donike 
hi bro, I also train the AE with config file  **kl-f4/config.yaml**
and the loss seems to drop normally, the reconstruction gs is normal, but the sample of AE is just unnormal. 
So how to judge whether the AE is trained well and no more epochs needed ？

**Comment by OwalnutO** [comment]
> > Hello @SoHotLB, yes the loss keeps decreasing during the training process. What's a bit tricky is that the recreation loss seems to plateausbefore the KL divergence loss, leading to the issues I encountered in the original ticket opened in this thread.
> > Dont mind the absloute loss values, i'm using multispectral images with >3 bands. ~200k images. I heavily modified the repo and how it handles the config files, so i doubt that would be useful for you, sorry. <img alt="ls" width="850" src="https://user-images.githubusercontent.com/65158680/252290974-04bb9c20-ee4c-4c4f-85e9-2aedaa0df040.png">
> 
> ok, thanks for your reply. At the same time, I want to know if outputting `pop from empty list` during training affects the result.

Hi~I'm curious that do you modify the loss fucntion when training the AE? I also try to train the AE on my own dataset but I got some wried resutls as mentioned in #309 . Could you give some suggestions? Thanks!

**Comment by liangbingzhao** [comment]
Hi @simon-donike, I wonder how to judge when the training of AE is enough for Unet training? Need to try to train the Unet to find out?

**Comment by simon-donike** [comment]
@liangbingzhao for me the KL was very helpful in figuring that out. If your dataset is large, diverse and well balanced enough not to worry about overfitting I would also just let it continue to train longer than one might think. But of course at the end the only way of knowing for sure is training the UNet ...

**Comment by liangbingzhao** [comment]
> @liangbingzhao for me the KL was very helpful in figuring that out. If your dataset is large, diverse and well balanced enough not to worry about overfitting I would also just let it continue to train longer than one might think. But of course at the end the only way of knowing for sure is training the UNet ...

Thx for your reply. Have u tried to train the VQGAN, it does not have kl loss, then how to judge that?

**Comment by ezra-ch** [comment]
Whats the training code senpai  @simon-donike. Im trying to add more channels to the AE. My current train code just gives me noise.

**Comment by simon-donike** [comment]
@ezra-ch As mentioned above, wrap the instanciated model in a lightning Trainer with your data. The problem is the loss since the LPIPS obviously cant accept anything else than 3 bands. So you need to come up with meaningful losses that also capture a perceptual metric. Without the GAN component I did not get good results, so I suggest keeping that but replace the LPIPS with another metric.

**Comment by wtliao** [comment]
@simon-donike thanks a lot for sharing your training experience. It is very helpful. I am also trying to train my AE and I have several questions.
First, my traing loss seems very unstable 
train/total_loss
![newplot](https://github.com/CompVis/latent-diffusion/assets/4618954/9182160c-ffdb-4bf9-b51c-4a83130e1c68)
train/kl_loss
![newplot (1)](https://github.com/CompVis/latent-diffusion/assets/4618954/1d2dde56-010f-4dd1-a493-d971c261103c)
train/rec_loss
![newplot (2)](https://github.com/CompVis/latent-diffusion/assets/4618954/9b5745a5-e2ce-4424-bff5-6fd01ca049d6)

However, the val loss curves seem much better
val/total_loss
![newplot (3)](https://github.com/CompVis/latent-diffusion/assets/4618954/12ef23da-295e-49d3-b2f3-9b208fd4840a)
val/rec_loss
![newplot (4)](https://github.com/CompVis/latent-diffusion/assets/4618954/ccea2a78-4f5f-4f83-9994-d455d2e5dcc7)
val/kl_loss
![newplot (5)](https://github.com/CompVis/latent-diffusion/assets/4618954/c174e173-aeb4-4c62-a06b-c8806cf94108)

I have no idea why they like this.

Second, in the original config file in https://github.com/CompVis/latent-diffusion/blob/main/models/first_stage_models/kl-f8/config.yaml, it seems that the training images are first randomly cropped in size of 256 and then upsampled to 384, i.e. 1.5x. I dont do this step, and just keep all input image in size of 512. How do you process the training image?

Third, I am using fixed LR as the config file. You mentioned that "didn't get good results with a fixed LR or with linear schedules", so could you share your config file to me to learn how to set the learning schedule as well as the data process? Thanks in advance!

**Comment by simon-donike** [comment]
@wtliao 
1. Looks okay to me, maby oscillations due to low batch size? And it seems like you're asynchroniously logging to wandb, which might be why you have different timestep gaps? but the val metrics seem to improve nicely dont you think?
2. I dont use f8, just my own dataset/dataloader classes that provide the images in native 512. I don't know how their data handling works
3. check the [configure_optimizers](https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/models/autoencoder.py#L211) funciton. Maybe set _self.scheduler_config_ to use a scheduler in your config file. personally, I changed a lot and don't use their config, so I cant provide you an example. Maybe also conisder just hard-coding a ReduceLRonPlateu in the configure_optimizers to avoid the config alltogether. E.g:
```
  # set LR scheduler
            scheduler_ae = {
                'scheduler': torch.optim.lr_scheduler.ReduceLROnPlateau(opt_ae, mode='min', factor=0.5, patience=patience),
                'interval': 'epoch',
                'monitor':'val/total_loss',
                'strict': True,
                    }

            scheduler_disc = {
                'scheduler': torch.optim.lr_scheduler.ReduceLROnPlateau(opt_disc, mode='min', factor=0.5, patience=patience),
                'interval': 'epoch',
                'monitor':'val/total_loss',  
                'strict': True,
            }
```
Note: pytorch lightning >1.9 doesnt support the `return [opt_ae, opt_disc], [scheduler_ae,scheduler_disc]` way of setting optims anymore.
hope this helps!

**Comment by wtliao** [comment]
@simon-donike many thanks for your swift reply. Are you using VQ autoencoder or the normal one?

**Comment by simon-donike** [comment]
@wtliao AutoencoderKL

**Comment by wtliao** [comment]
@simon-donike after reading the official doc, I found that ReduceLROnPlateau will check the monitor metric by epoch and then reduce the lr after patience epochs if the monitor metric does not reduce. Is it possible to set 'interval' as 'step' and patience=1000, so that if after 1000 steps the loss does not reduce, than reduce the lr? Because I have around 1B images, monitor the metric by epoch is impractical.

**Comment by taustudent** [comment]
> @wtliao AutoencoderKL

Hi
I also used AE-KL and trained it from scratch, but then when I tried to train LDM based on this AE, I got into configuration problems. seems that the configuration of the LDM don't match to the AE configuration. Do you know how to match between them? or how to choose the right configs files? I'm trying to train AE+LDM for class-conditional image generation' I used configs/autoencoder/autoencoder_kl_16x16x16.yaml for the AE, and configs/latent-diffusion/lsun_churches-ldm-kl-8.yaml for the LDM.
thanks

**Comment by wtliao** [comment]
> > @wtliao AutoencoderKL
> 
> Hi I also used AE-KL and trained it from scratch, but then when I tried to train LDM based on this AE, I got into configuration problems. seems that the configuration of the LDM don't match to the AE configuration. Do you know how to match between them? or how to choose the right configs files? I'm trying to train AE+LDM for class-conditional image generation' I used configs/autoencoder/autoencoder_kl_16x16x16.yaml for the AE, and configs/latent-diffusion/lsun_churches-ldm-kl-8.yaml for the LDM. thanks

You need to change your Unet input and output channels as 16 so that it matches to your AE latent channel. It should be set in line 33 and 34 (https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/configs/latent-diffusion/lsun_churches-ldm-kl-8.yaml#L33) of the config file.

**Comment by simon-donike** [comment]
> @simon-donike after reading the official doc, I found that ReduceLROnPlateau will check the monitor metric by epoch and then reduce the lr after patience epochs if the monitor metric does not reduce. Is it possible to set 'interval' as 'step' and patience=1000, so that if after 1000 steps the loss does not reduce, than reduce the lr? Because I have around 1B images, monitor the metric by epoch is impractical. 

@wtliao Yes exactly

**Comment by wtliao** [comment]
@simon-donike ， Btw, regarding the metrics for AE-KL, what is PSIM? perceptual similarity? what is its difference  from LPISP? Thanks again.

**Comment by TorAP** [comment]
Hi @simon-donike, 

I hope it is alright I ask in this thread. Whenever I sample from a self-trained an LDM with a pretrained Autoencoder I get cropped images. Any idea to why this is happening? I sample through scripts/diffusion.py.  

My input images are 1850x1150

I used: 

configs/ autoencoder/autoencoder_kl_8x8x64.yaml

and this config to train the ldm: 
```
model:
  base_learning_rate: 5.0e-5   # set to target_lr by starting main.py with '--scale_lr False'
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    first_stage_key: "image"
    cond_stage_key: "image"
    image_size: 32
    channels: 4
    cond_stage_trainable: False
    concat_mode: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [ 1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 192
        attention_resolutions: [ 1, 2, 4, 8 ]   # 32, 16, 8, 4
        num_res_blocks: 2
        channel_mult: [ 1,2,2,4,4 ]  # 32, 16, 8, 4, 2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: "models/first_stage_models/kl-f8/model.ckpt"
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: [ ]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_unconditional__"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 1
    wrap: False
    train:
      target: ldm.data.dataloader.VialTrain
      params:
        size: 256
    validation:
      target: ldm.data.dataloader.VialVal
      params:
        size: 256

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False


  trainer:
    benchmark: True

```
