### ISSUE TITLE
Question about log_images() on validation_batch_end

### ISSUE THREAD

**Issue by Lucarqi** [CompVis/latent-diffusion#370]
how can I save input images and recon images on the validation process end. In code, it seems will save by **class ImageLogger** in function **on_validation_batch_end()**. And, **on_train_batch_end()**. works good , save images in every *batch_frequency*.
Here is my config file in ```/configs/autoencoder```.
```
model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: "val/rec_loss"
    embed_dim: 4
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 30001
        kl_weight: 0.000001
        disc_weight: 0.5

    ddconfig:
      double_z: True
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    wrap: True
    train:
      target: ldm.data.renji.RenJiTrain
    validation:
      target: ldm.data.renji.RenJiValidation


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
```
